package testException;

public class TestExce extends Exception {
    //í自定义异常
    public TestExce(){

    }
    public TestExce(String msg) {
        super(msg);
    }


    public static void main(String[] args) {
//        int i = method1();
//        System.out.println(i);



    }

//    public static int method1() {
//        try {
//            return 1;
//        }catch (Exception e){
//            return 2;
//        }finally {
//            return 3;
//        }
//    }
}
